# Default, Defaults
markdown: redcarpet
highlighter: pygments # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]
baseurl: "/x-market" # the subpath of your site, e.g. /blog

# Jekyll Defaults
title: Little Big Blue
email: your-email@domain.com
description: ooo

twitter:
facebook:
google:
